/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as HelpdeskIndexRouteImport } from './routes/helpdesk.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsCompanyRouteImport } from './routes/settings.company'
import { Route as SalesQuotationsRouteImport } from './routes/sales.quotations'
import { Route as SalesPaymentsRouteImport } from './routes/sales.payments'
import { Route as SalesOrdersRouteImport } from './routes/sales.orders'
import { Route as SalesInvoicesRouteImport } from './routes/sales.invoices'
import { Route as ReportsSalesRouteImport } from './routes/reports.sales'
import { Route as ReportsInventoryRouteImport } from './routes/reports.inventory'
import { Route as ReportsHrRouteImport } from './routes/reports.hr'
import { Route as ReportsFinanceRouteImport } from './routes/reports.finance'
import { Route as ReportsCrmRouteImport } from './routes/reports.crm'
import { Route as RecruitmentPipelineRouteImport } from './routes/recruitment.pipeline'
import { Route as RecruitmentJobsRouteImport } from './routes/recruitment.jobs'
import { Route as RecruitmentInterviewsRouteImport } from './routes/recruitment.interviews'
import { Route as RecruitmentCandidatesRouteImport } from './routes/recruitment.candidates'
import { Route as PurchasesVendorsRouteImport } from './routes/purchases.vendors'
import { Route as PurchasesRequestsRouteImport } from './routes/purchases.requests'
import { Route as PurchasesOrdersRouteImport } from './routes/purchases.orders'
import { Route as PurchasesAnalyticsRouteImport } from './routes/purchases.analytics'
import { Route as ProjectsTeamRouteImport } from './routes/projects.team'
import { Route as ProjectsTasksRouteImport } from './routes/projects.tasks'
import { Route as ProjectsKanbanRouteImport } from './routes/projects.kanban'
import { Route as ProjectsGanttRouteImport } from './routes/projects.gantt'
import { Route as InventoryWarehousesRouteImport } from './routes/inventory.warehouses'
import { Route as InventoryProductsRouteImport } from './routes/inventory.products'
import { Route as InventoryMovementsRouteImport } from './routes/inventory.movements'
import { Route as InventoryCategoriesRouteImport } from './routes/inventory.categories'
import { Route as HrPayrollRouteImport } from './routes/hr.payroll'
import { Route as HrLeaveRouteImport } from './routes/hr.leave'
import { Route as HrEmployeesRouteImport } from './routes/hr.employees'
import { Route as HrDesignationsRouteImport } from './routes/hr.designations'
import { Route as HrDepartmentsRouteImport } from './routes/hr.departments'
import { Route as HrAttendanceRouteImport } from './routes/hr.attendance'
import { Route as HelpdeskTicketsRouteImport } from './routes/helpdesk.tickets'
import { Route as HelpdeskKbRouteImport } from './routes/helpdesk.kb'
import { Route as FinanceTransactionsRouteImport } from './routes/finance.transactions'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as FinanceIncomeRouteImport } from './routes/finance.income'
import { Route as FinanceExpensesRouteImport } from './routes/finance.expenses'
import { Route as FinanceBudgetsRouteImport } from './routes/finance.budgets'
import { Route as FinanceAccountsRouteImport } from './routes/finance.accounts'
import { Route as DocumentsSharedRouteImport } from './routes/documents.shared'
import { Route as DocumentsRecentRouteImport } from './routes/documents.recent'
import { Route as DocumentsFoldersRouteImport } from './routes/documents.folders'
import { Route as DocumentsFilesRouteImport } from './routes/documents.files'
import { Route as CustomersAnalyticsRouteImport } from './routes/customers.analytics'
import { Route as CustomersActivitiesRouteImport } from './routes/customers.activities'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmDealsRouteImport } from './routes/crm.deals'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmCompaniesRouteImport } from './routes/crm.companies'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AnalyticsRevenueRouteImport } from './routes/analytics.revenue'
import { Route as AnalyticsInventoryRouteImport } from './routes/analytics.inventory'
import { Route as AnalyticsEmployeesRouteImport } from './routes/analytics.employees'
import { Route as AnalyticsCustomersRouteImport } from './routes/analytics.customers'
import { Route as AccountingTrialBalanceRouteImport } from './routes/accounting.trial-balance'
import { Route as AccountingPnlRouteImport } from './routes/accounting.pnl'
import { Route as AccountingLedgerRouteImport } from './routes/accounting.ledger'
import { Route as AccountingJournalRouteImport } from './routes/accounting.journal'
import { Route as AccountingBalanceSheetRouteImport } from './routes/accounting.balance-sheet'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskIndexRoute = HelpdeskIndexRouteImport.update({
  id: '/helpdesk/',
  path: '/helpdesk/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCompanyRoute = SettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQuotationsRoute = SalesQuotationsRouteImport.update({
  id: '/sales/quotations',
  path: '/sales/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPaymentsRoute = SalesPaymentsRouteImport.update({
  id: '/sales/payments',
  path: '/sales/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales/orders',
  path: '/sales/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoicesRoute = SalesInvoicesRouteImport.update({
  id: '/sales/invoices',
  path: '/sales/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsInventoryRoute = ReportsInventoryRouteImport.update({
  id: '/reports/inventory',
  path: '/reports/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsHrRoute = ReportsHrRouteImport.update({
  id: '/reports/hr',
  path: '/reports/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFinanceRoute = ReportsFinanceRouteImport.update({
  id: '/reports/finance',
  path: '/reports/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCrmRoute = ReportsCrmRouteImport.update({
  id: '/reports/crm',
  path: '/reports/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentPipelineRoute = RecruitmentPipelineRouteImport.update({
  id: '/recruitment/pipeline',
  path: '/recruitment/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentJobsRoute = RecruitmentJobsRouteImport.update({
  id: '/recruitment/jobs',
  path: '/recruitment/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentInterviewsRoute = RecruitmentInterviewsRouteImport.update({
  id: '/recruitment/interviews',
  path: '/recruitment/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentCandidatesRoute = RecruitmentCandidatesRouteImport.update({
  id: '/recruitment/candidates',
  path: '/recruitment/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesVendorsRoute = PurchasesVendorsRouteImport.update({
  id: '/purchases/vendors',
  path: '/purchases/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRequestsRoute = PurchasesRequestsRouteImport.update({
  id: '/purchases/requests',
  path: '/purchases/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesOrdersRoute = PurchasesOrdersRouteImport.update({
  id: '/purchases/orders',
  path: '/purchases/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesAnalyticsRoute = PurchasesAnalyticsRouteImport.update({
  id: '/purchases/analytics',
  path: '/purchases/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTeamRoute = ProjectsTeamRouteImport.update({
  id: '/projects/team',
  path: '/projects/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTasksRoute = ProjectsTasksRouteImport.update({
  id: '/projects/tasks',
  path: '/projects/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsKanbanRoute = ProjectsKanbanRouteImport.update({
  id: '/projects/kanban',
  path: '/projects/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsGanttRoute = ProjectsGanttRouteImport.update({
  id: '/projects/gantt',
  path: '/projects/gantt',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryWarehousesRoute = InventoryWarehousesRouteImport.update({
  id: '/inventory/warehouses',
  path: '/inventory/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsRoute = InventoryProductsRouteImport.update({
  id: '/inventory/products',
  path: '/inventory/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryMovementsRoute = InventoryMovementsRouteImport.update({
  id: '/inventory/movements',
  path: '/inventory/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryCategoriesRoute = InventoryCategoriesRouteImport.update({
  id: '/inventory/categories',
  path: '/inventory/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HrLeaveRoute = HrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEmployeesRoute = HrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDesignationsRoute = HrDesignationsRouteImport.update({
  id: '/hr/designations',
  path: '/hr/designations',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDepartmentsRoute = HrDepartmentsRouteImport.update({
  id: '/hr/departments',
  path: '/hr/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const HrAttendanceRoute = HrAttendanceRouteImport.update({
  id: '/hr/attendance',
  path: '/hr/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskTicketsRoute = HelpdeskTicketsRouteImport.update({
  id: '/helpdesk/tickets',
  path: '/helpdesk/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskKbRoute = HelpdeskKbRouteImport.update({
  id: '/helpdesk/kb',
  path: '/helpdesk/kb',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTransactionsRoute = FinanceTransactionsRouteImport.update({
  id: '/finance/transactions',
  path: '/finance/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/finance/reports',
  path: '/finance/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIncomeRoute = FinanceIncomeRouteImport.update({
  id: '/finance/income',
  path: '/finance/income',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBudgetsRoute = FinanceBudgetsRouteImport.update({
  id: '/finance/budgets',
  path: '/finance/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/finance/accounts',
  path: '/finance/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsSharedRoute = DocumentsSharedRouteImport.update({
  id: '/documents/shared',
  path: '/documents/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRecentRoute = DocumentsRecentRouteImport.update({
  id: '/documents/recent',
  path: '/documents/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsFoldersRoute = DocumentsFoldersRouteImport.update({
  id: '/documents/folders',
  path: '/documents/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsFilesRoute = DocumentsFilesRouteImport.update({
  id: '/documents/files',
  path: '/documents/files',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersAnalyticsRoute = CustomersAnalyticsRouteImport.update({
  id: '/customers/analytics',
  path: '/customers/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersActivitiesRoute = CustomersActivitiesRouteImport.update({
  id: '/customers/activities',
  path: '/customers/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmDealsRoute = CrmDealsRouteImport.update({
  id: '/crm/deals',
  path: '/crm/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCompaniesRoute = CrmCompaniesRouteImport.update({
  id: '/crm/companies',
  path: '/crm/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRevenueRoute = AnalyticsRevenueRouteImport.update({
  id: '/analytics/revenue',
  path: '/analytics/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsInventoryRoute = AnalyticsInventoryRouteImport.update({
  id: '/analytics/inventory',
  path: '/analytics/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsEmployeesRoute = AnalyticsEmployeesRouteImport.update({
  id: '/analytics/employees',
  path: '/analytics/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsCustomersRoute = AnalyticsCustomersRouteImport.update({
  id: '/analytics/customers',
  path: '/analytics/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingTrialBalanceRoute = AccountingTrialBalanceRouteImport.update({
  id: '/accounting/trial-balance',
  path: '/accounting/trial-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingPnlRoute = AccountingPnlRouteImport.update({
  id: '/accounting/pnl',
  path: '/accounting/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingLedgerRoute = AccountingLedgerRouteImport.update({
  id: '/accounting/ledger',
  path: '/accounting/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingJournalRoute = AccountingJournalRouteImport.update({
  id: '/accounting/journal',
  path: '/accounting/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingBalanceSheetRoute = AccountingBalanceSheetRouteImport.update({
  id: '/accounting/balance-sheet',
  path: '/accounting/balance-sheet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/journal': typeof AccountingJournalRoute
  '/accounting/ledger': typeof AccountingLedgerRoute
  '/accounting/pnl': typeof AccountingPnlRoute
  '/accounting/trial-balance': typeof AccountingTrialBalanceRoute
  '/analytics/customers': typeof AnalyticsCustomersRoute
  '/analytics/employees': typeof AnalyticsEmployeesRoute
  '/analytics/inventory': typeof AnalyticsInventoryRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/api/chat': typeof ApiChatRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/customers/activities': typeof CustomersActivitiesRoute
  '/customers/analytics': typeof CustomersAnalyticsRoute
  '/documents/files': typeof DocumentsFilesRoute
  '/documents/folders': typeof DocumentsFoldersRoute
  '/documents/recent': typeof DocumentsRecentRoute
  '/documents/shared': typeof DocumentsSharedRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/helpdesk/kb': typeof HelpdeskKbRoute
  '/helpdesk/tickets': typeof HelpdeskTicketsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/departments': typeof HrDepartmentsRoute
  '/hr/designations': typeof HrDesignationsRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/leave': typeof HrLeaveRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/inventory/categories': typeof InventoryCategoriesRoute
  '/inventory/movements': typeof InventoryMovementsRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/projects/gantt': typeof ProjectsGanttRoute
  '/projects/kanban': typeof ProjectsKanbanRoute
  '/projects/tasks': typeof ProjectsTasksRoute
  '/projects/team': typeof ProjectsTeamRoute
  '/purchases/analytics': typeof PurchasesAnalyticsRoute
  '/purchases/orders': typeof PurchasesOrdersRoute
  '/purchases/requests': typeof PurchasesRequestsRoute
  '/purchases/vendors': typeof PurchasesVendorsRoute
  '/recruitment/candidates': typeof RecruitmentCandidatesRoute
  '/recruitment/interviews': typeof RecruitmentInterviewsRoute
  '/recruitment/jobs': typeof RecruitmentJobsRoute
  '/recruitment/pipeline': typeof RecruitmentPipelineRoute
  '/reports/crm': typeof ReportsCrmRoute
  '/reports/finance': typeof ReportsFinanceRoute
  '/reports/hr': typeof ReportsHrRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/sales/invoices': typeof SalesInvoicesRoute
  '/sales/orders': typeof SalesOrdersRoute
  '/sales/payments': typeof SalesPaymentsRoute
  '/sales/quotations': typeof SalesQuotationsRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/users': typeof SettingsUsersRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/helpdesk/': typeof HelpdeskIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/journal': typeof AccountingJournalRoute
  '/accounting/ledger': typeof AccountingLedgerRoute
  '/accounting/pnl': typeof AccountingPnlRoute
  '/accounting/trial-balance': typeof AccountingTrialBalanceRoute
  '/analytics/customers': typeof AnalyticsCustomersRoute
  '/analytics/employees': typeof AnalyticsEmployeesRoute
  '/analytics/inventory': typeof AnalyticsInventoryRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/api/chat': typeof ApiChatRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/customers/activities': typeof CustomersActivitiesRoute
  '/customers/analytics': typeof CustomersAnalyticsRoute
  '/documents/files': typeof DocumentsFilesRoute
  '/documents/folders': typeof DocumentsFoldersRoute
  '/documents/recent': typeof DocumentsRecentRoute
  '/documents/shared': typeof DocumentsSharedRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/helpdesk/kb': typeof HelpdeskKbRoute
  '/helpdesk/tickets': typeof HelpdeskTicketsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/departments': typeof HrDepartmentsRoute
  '/hr/designations': typeof HrDesignationsRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/leave': typeof HrLeaveRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/inventory/categories': typeof InventoryCategoriesRoute
  '/inventory/movements': typeof InventoryMovementsRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/projects/gantt': typeof ProjectsGanttRoute
  '/projects/kanban': typeof ProjectsKanbanRoute
  '/projects/tasks': typeof ProjectsTasksRoute
  '/projects/team': typeof ProjectsTeamRoute
  '/purchases/analytics': typeof PurchasesAnalyticsRoute
  '/purchases/orders': typeof PurchasesOrdersRoute
  '/purchases/requests': typeof PurchasesRequestsRoute
  '/purchases/vendors': typeof PurchasesVendorsRoute
  '/recruitment/candidates': typeof RecruitmentCandidatesRoute
  '/recruitment/interviews': typeof RecruitmentInterviewsRoute
  '/recruitment/jobs': typeof RecruitmentJobsRoute
  '/recruitment/pipeline': typeof RecruitmentPipelineRoute
  '/reports/crm': typeof ReportsCrmRoute
  '/reports/finance': typeof ReportsFinanceRoute
  '/reports/hr': typeof ReportsHrRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/sales/invoices': typeof SalesInvoicesRoute
  '/sales/orders': typeof SalesOrdersRoute
  '/sales/payments': typeof SalesPaymentsRoute
  '/sales/quotations': typeof SalesQuotationsRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/users': typeof SettingsUsersRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/helpdesk': typeof HelpdeskIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/journal': typeof AccountingJournalRoute
  '/accounting/ledger': typeof AccountingLedgerRoute
  '/accounting/pnl': typeof AccountingPnlRoute
  '/accounting/trial-balance': typeof AccountingTrialBalanceRoute
  '/analytics/customers': typeof AnalyticsCustomersRoute
  '/analytics/employees': typeof AnalyticsEmployeesRoute
  '/analytics/inventory': typeof AnalyticsInventoryRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/api/chat': typeof ApiChatRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/customers/activities': typeof CustomersActivitiesRoute
  '/customers/analytics': typeof CustomersAnalyticsRoute
  '/documents/files': typeof DocumentsFilesRoute
  '/documents/folders': typeof DocumentsFoldersRoute
  '/documents/recent': typeof DocumentsRecentRoute
  '/documents/shared': typeof DocumentsSharedRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/helpdesk/kb': typeof HelpdeskKbRoute
  '/helpdesk/tickets': typeof HelpdeskTicketsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/departments': typeof HrDepartmentsRoute
  '/hr/designations': typeof HrDesignationsRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/leave': typeof HrLeaveRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/inventory/categories': typeof InventoryCategoriesRoute
  '/inventory/movements': typeof InventoryMovementsRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/projects/gantt': typeof ProjectsGanttRoute
  '/projects/kanban': typeof ProjectsKanbanRoute
  '/projects/tasks': typeof ProjectsTasksRoute
  '/projects/team': typeof ProjectsTeamRoute
  '/purchases/analytics': typeof PurchasesAnalyticsRoute
  '/purchases/orders': typeof PurchasesOrdersRoute
  '/purchases/requests': typeof PurchasesRequestsRoute
  '/purchases/vendors': typeof PurchasesVendorsRoute
  '/recruitment/candidates': typeof RecruitmentCandidatesRoute
  '/recruitment/interviews': typeof RecruitmentInterviewsRoute
  '/recruitment/jobs': typeof RecruitmentJobsRoute
  '/recruitment/pipeline': typeof RecruitmentPipelineRoute
  '/reports/crm': typeof ReportsCrmRoute
  '/reports/finance': typeof ReportsFinanceRoute
  '/reports/hr': typeof ReportsHrRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/sales/invoices': typeof SalesInvoicesRoute
  '/sales/orders': typeof SalesOrdersRoute
  '/sales/payments': typeof SalesPaymentsRoute
  '/sales/quotations': typeof SalesQuotationsRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/users': typeof SettingsUsersRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/helpdesk/': typeof HelpdeskIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/features'
    | '/modules'
    | '/pricing'
    | '/accounting/balance-sheet'
    | '/accounting/journal'
    | '/accounting/ledger'
    | '/accounting/pnl'
    | '/accounting/trial-balance'
    | '/analytics/customers'
    | '/analytics/employees'
    | '/analytics/inventory'
    | '/analytics/revenue'
    | '/api/chat'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/leads'
    | '/customers/activities'
    | '/customers/analytics'
    | '/documents/files'
    | '/documents/folders'
    | '/documents/recent'
    | '/documents/shared'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/expenses'
    | '/finance/income'
    | '/finance/reports'
    | '/finance/transactions'
    | '/helpdesk/kb'
    | '/helpdesk/tickets'
    | '/hr/attendance'
    | '/hr/departments'
    | '/hr/designations'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/payroll'
    | '/inventory/categories'
    | '/inventory/movements'
    | '/inventory/products'
    | '/inventory/warehouses'
    | '/projects/gantt'
    | '/projects/kanban'
    | '/projects/tasks'
    | '/projects/team'
    | '/purchases/analytics'
    | '/purchases/orders'
    | '/purchases/requests'
    | '/purchases/vendors'
    | '/recruitment/candidates'
    | '/recruitment/interviews'
    | '/recruitment/jobs'
    | '/recruitment/pipeline'
    | '/reports/crm'
    | '/reports/finance'
    | '/reports/hr'
    | '/reports/inventory'
    | '/reports/sales'
    | '/sales/invoices'
    | '/sales/orders'
    | '/sales/payments'
    | '/sales/quotations'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/users'
    | '/analytics/'
    | '/customers/'
    | '/helpdesk/'
    | '/inventory/'
    | '/projects/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/features'
    | '/modules'
    | '/pricing'
    | '/accounting/balance-sheet'
    | '/accounting/journal'
    | '/accounting/ledger'
    | '/accounting/pnl'
    | '/accounting/trial-balance'
    | '/analytics/customers'
    | '/analytics/employees'
    | '/analytics/inventory'
    | '/analytics/revenue'
    | '/api/chat'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/leads'
    | '/customers/activities'
    | '/customers/analytics'
    | '/documents/files'
    | '/documents/folders'
    | '/documents/recent'
    | '/documents/shared'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/expenses'
    | '/finance/income'
    | '/finance/reports'
    | '/finance/transactions'
    | '/helpdesk/kb'
    | '/helpdesk/tickets'
    | '/hr/attendance'
    | '/hr/departments'
    | '/hr/designations'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/payroll'
    | '/inventory/categories'
    | '/inventory/movements'
    | '/inventory/products'
    | '/inventory/warehouses'
    | '/projects/gantt'
    | '/projects/kanban'
    | '/projects/tasks'
    | '/projects/team'
    | '/purchases/analytics'
    | '/purchases/orders'
    | '/purchases/requests'
    | '/purchases/vendors'
    | '/recruitment/candidates'
    | '/recruitment/interviews'
    | '/recruitment/jobs'
    | '/recruitment/pipeline'
    | '/reports/crm'
    | '/reports/finance'
    | '/reports/hr'
    | '/reports/inventory'
    | '/reports/sales'
    | '/sales/invoices'
    | '/sales/orders'
    | '/sales/payments'
    | '/sales/quotations'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/users'
    | '/analytics'
    | '/customers'
    | '/helpdesk'
    | '/inventory'
    | '/projects'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/features'
    | '/modules'
    | '/pricing'
    | '/accounting/balance-sheet'
    | '/accounting/journal'
    | '/accounting/ledger'
    | '/accounting/pnl'
    | '/accounting/trial-balance'
    | '/analytics/customers'
    | '/analytics/employees'
    | '/analytics/inventory'
    | '/analytics/revenue'
    | '/api/chat'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/leads'
    | '/customers/activities'
    | '/customers/analytics'
    | '/documents/files'
    | '/documents/folders'
    | '/documents/recent'
    | '/documents/shared'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/expenses'
    | '/finance/income'
    | '/finance/reports'
    | '/finance/transactions'
    | '/helpdesk/kb'
    | '/helpdesk/tickets'
    | '/hr/attendance'
    | '/hr/departments'
    | '/hr/designations'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/payroll'
    | '/inventory/categories'
    | '/inventory/movements'
    | '/inventory/products'
    | '/inventory/warehouses'
    | '/projects/gantt'
    | '/projects/kanban'
    | '/projects/tasks'
    | '/projects/team'
    | '/purchases/analytics'
    | '/purchases/orders'
    | '/purchases/requests'
    | '/purchases/vendors'
    | '/recruitment/candidates'
    | '/recruitment/interviews'
    | '/recruitment/jobs'
    | '/recruitment/pipeline'
    | '/reports/crm'
    | '/reports/finance'
    | '/reports/hr'
    | '/reports/inventory'
    | '/reports/sales'
    | '/sales/invoices'
    | '/sales/orders'
    | '/sales/payments'
    | '/sales/quotations'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/users'
    | '/analytics/'
    | '/customers/'
    | '/helpdesk/'
    | '/inventory/'
    | '/projects/'
    | '/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ModulesRoute: typeof ModulesRoute
  PricingRoute: typeof PricingRoute
  AccountingBalanceSheetRoute: typeof AccountingBalanceSheetRoute
  AccountingJournalRoute: typeof AccountingJournalRoute
  AccountingLedgerRoute: typeof AccountingLedgerRoute
  AccountingPnlRoute: typeof AccountingPnlRoute
  AccountingTrialBalanceRoute: typeof AccountingTrialBalanceRoute
  AnalyticsCustomersRoute: typeof AnalyticsCustomersRoute
  AnalyticsEmployeesRoute: typeof AnalyticsEmployeesRoute
  AnalyticsInventoryRoute: typeof AnalyticsInventoryRoute
  AnalyticsRevenueRoute: typeof AnalyticsRevenueRoute
  ApiChatRoute: typeof ApiChatRoute
  CrmCompaniesRoute: typeof CrmCompaniesRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmDealsRoute: typeof CrmDealsRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CustomersActivitiesRoute: typeof CustomersActivitiesRoute
  CustomersAnalyticsRoute: typeof CustomersAnalyticsRoute
  DocumentsFilesRoute: typeof DocumentsFilesRoute
  DocumentsFoldersRoute: typeof DocumentsFoldersRoute
  DocumentsRecentRoute: typeof DocumentsRecentRoute
  DocumentsSharedRoute: typeof DocumentsSharedRoute
  FinanceAccountsRoute: typeof FinanceAccountsRoute
  FinanceBudgetsRoute: typeof FinanceBudgetsRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceIncomeRoute: typeof FinanceIncomeRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FinanceTransactionsRoute: typeof FinanceTransactionsRoute
  HelpdeskKbRoute: typeof HelpdeskKbRoute
  HelpdeskTicketsRoute: typeof HelpdeskTicketsRoute
  HrAttendanceRoute: typeof HrAttendanceRoute
  HrDepartmentsRoute: typeof HrDepartmentsRoute
  HrDesignationsRoute: typeof HrDesignationsRoute
  HrEmployeesRoute: typeof HrEmployeesRoute
  HrLeaveRoute: typeof HrLeaveRoute
  HrPayrollRoute: typeof HrPayrollRoute
  InventoryCategoriesRoute: typeof InventoryCategoriesRoute
  InventoryMovementsRoute: typeof InventoryMovementsRoute
  InventoryProductsRoute: typeof InventoryProductsRoute
  InventoryWarehousesRoute: typeof InventoryWarehousesRoute
  ProjectsGanttRoute: typeof ProjectsGanttRoute
  ProjectsKanbanRoute: typeof ProjectsKanbanRoute
  ProjectsTasksRoute: typeof ProjectsTasksRoute
  ProjectsTeamRoute: typeof ProjectsTeamRoute
  PurchasesAnalyticsRoute: typeof PurchasesAnalyticsRoute
  PurchasesOrdersRoute: typeof PurchasesOrdersRoute
  PurchasesRequestsRoute: typeof PurchasesRequestsRoute
  PurchasesVendorsRoute: typeof PurchasesVendorsRoute
  RecruitmentCandidatesRoute: typeof RecruitmentCandidatesRoute
  RecruitmentInterviewsRoute: typeof RecruitmentInterviewsRoute
  RecruitmentJobsRoute: typeof RecruitmentJobsRoute
  RecruitmentPipelineRoute: typeof RecruitmentPipelineRoute
  ReportsCrmRoute: typeof ReportsCrmRoute
  ReportsFinanceRoute: typeof ReportsFinanceRoute
  ReportsHrRoute: typeof ReportsHrRoute
  ReportsInventoryRoute: typeof ReportsInventoryRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
  SalesInvoicesRoute: typeof SalesInvoicesRoute
  SalesOrdersRoute: typeof SalesOrdersRoute
  SalesPaymentsRoute: typeof SalesPaymentsRoute
  SalesQuotationsRoute: typeof SalesQuotationsRoute
  SettingsCompanyRoute: typeof SettingsCompanyRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  HelpdeskIndexRoute: typeof HelpdeskIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk/': {
      id: '/helpdesk/'
      path: '/helpdesk'
      fullPath: '/helpdesk/'
      preLoaderRoute: typeof HelpdeskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/company': {
      id: '/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof SettingsCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/quotations': {
      id: '/sales/quotations'
      path: '/sales/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof SalesQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/payments': {
      id: '/sales/payments'
      path: '/sales/payments'
      fullPath: '/sales/payments'
      preLoaderRoute: typeof SalesPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/orders': {
      id: '/sales/orders'
      path: '/sales/orders'
      fullPath: '/sales/orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/invoices': {
      id: '/sales/invoices'
      path: '/sales/invoices'
      fullPath: '/sales/invoices'
      preLoaderRoute: typeof SalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/inventory': {
      id: '/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof ReportsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/hr': {
      id: '/reports/hr'
      path: '/reports/hr'
      fullPath: '/reports/hr'
      preLoaderRoute: typeof ReportsHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/finance': {
      id: '/reports/finance'
      path: '/reports/finance'
      fullPath: '/reports/finance'
      preLoaderRoute: typeof ReportsFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/crm': {
      id: '/reports/crm'
      path: '/reports/crm'
      fullPath: '/reports/crm'
      preLoaderRoute: typeof ReportsCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/pipeline': {
      id: '/recruitment/pipeline'
      path: '/recruitment/pipeline'
      fullPath: '/recruitment/pipeline'
      preLoaderRoute: typeof RecruitmentPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/jobs': {
      id: '/recruitment/jobs'
      path: '/recruitment/jobs'
      fullPath: '/recruitment/jobs'
      preLoaderRoute: typeof RecruitmentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/interviews': {
      id: '/recruitment/interviews'
      path: '/recruitment/interviews'
      fullPath: '/recruitment/interviews'
      preLoaderRoute: typeof RecruitmentInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/candidates': {
      id: '/recruitment/candidates'
      path: '/recruitment/candidates'
      fullPath: '/recruitment/candidates'
      preLoaderRoute: typeof RecruitmentCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/vendors': {
      id: '/purchases/vendors'
      path: '/purchases/vendors'
      fullPath: '/purchases/vendors'
      preLoaderRoute: typeof PurchasesVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/requests': {
      id: '/purchases/requests'
      path: '/purchases/requests'
      fullPath: '/purchases/requests'
      preLoaderRoute: typeof PurchasesRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/orders': {
      id: '/purchases/orders'
      path: '/purchases/orders'
      fullPath: '/purchases/orders'
      preLoaderRoute: typeof PurchasesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/analytics': {
      id: '/purchases/analytics'
      path: '/purchases/analytics'
      fullPath: '/purchases/analytics'
      preLoaderRoute: typeof PurchasesAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/team': {
      id: '/projects/team'
      path: '/projects/team'
      fullPath: '/projects/team'
      preLoaderRoute: typeof ProjectsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/tasks': {
      id: '/projects/tasks'
      path: '/projects/tasks'
      fullPath: '/projects/tasks'
      preLoaderRoute: typeof ProjectsTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/kanban': {
      id: '/projects/kanban'
      path: '/projects/kanban'
      fullPath: '/projects/kanban'
      preLoaderRoute: typeof ProjectsKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/gantt': {
      id: '/projects/gantt'
      path: '/projects/gantt'
      fullPath: '/projects/gantt'
      preLoaderRoute: typeof ProjectsGanttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/warehouses': {
      id: '/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof InventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products': {
      id: '/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof InventoryProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/movements': {
      id: '/inventory/movements'
      path: '/inventory/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof InventoryMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/categories': {
      id: '/inventory/categories'
      path: '/inventory/categories'
      fullPath: '/inventory/categories'
      preLoaderRoute: typeof InventoryCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/leave': {
      id: '/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof HrLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/employees': {
      id: '/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof HrEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/designations': {
      id: '/hr/designations'
      path: '/hr/designations'
      fullPath: '/hr/designations'
      preLoaderRoute: typeof HrDesignationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/departments': {
      id: '/hr/departments'
      path: '/hr/departments'
      fullPath: '/hr/departments'
      preLoaderRoute: typeof HrDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/attendance': {
      id: '/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof HrAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk/tickets': {
      id: '/helpdesk/tickets'
      path: '/helpdesk/tickets'
      fullPath: '/helpdesk/tickets'
      preLoaderRoute: typeof HelpdeskTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk/kb': {
      id: '/helpdesk/kb'
      path: '/helpdesk/kb'
      fullPath: '/helpdesk/kb'
      preLoaderRoute: typeof HelpdeskKbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/transactions': {
      id: '/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof FinanceTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/finance/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/income': {
      id: '/finance/income'
      path: '/finance/income'
      fullPath: '/finance/income'
      preLoaderRoute: typeof FinanceIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/budgets': {
      id: '/finance/budgets'
      path: '/finance/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof FinanceBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/finance/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/shared': {
      id: '/documents/shared'
      path: '/documents/shared'
      fullPath: '/documents/shared'
      preLoaderRoute: typeof DocumentsSharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/recent': {
      id: '/documents/recent'
      path: '/documents/recent'
      fullPath: '/documents/recent'
      preLoaderRoute: typeof DocumentsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/folders': {
      id: '/documents/folders'
      path: '/documents/folders'
      fullPath: '/documents/folders'
      preLoaderRoute: typeof DocumentsFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/files': {
      id: '/documents/files'
      path: '/documents/files'
      fullPath: '/documents/files'
      preLoaderRoute: typeof DocumentsFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/analytics': {
      id: '/customers/analytics'
      path: '/customers/analytics'
      fullPath: '/customers/analytics'
      preLoaderRoute: typeof CustomersAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/activities': {
      id: '/customers/activities'
      path: '/customers/activities'
      fullPath: '/customers/activities'
      preLoaderRoute: typeof CustomersActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/deals': {
      id: '/crm/deals'
      path: '/crm/deals'
      fullPath: '/crm/deals'
      preLoaderRoute: typeof CrmDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/companies': {
      id: '/crm/companies'
      path: '/crm/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof CrmCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/revenue': {
      id: '/analytics/revenue'
      path: '/analytics/revenue'
      fullPath: '/analytics/revenue'
      preLoaderRoute: typeof AnalyticsRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/inventory': {
      id: '/analytics/inventory'
      path: '/analytics/inventory'
      fullPath: '/analytics/inventory'
      preLoaderRoute: typeof AnalyticsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/employees': {
      id: '/analytics/employees'
      path: '/analytics/employees'
      fullPath: '/analytics/employees'
      preLoaderRoute: typeof AnalyticsEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/customers': {
      id: '/analytics/customers'
      path: '/analytics/customers'
      fullPath: '/analytics/customers'
      preLoaderRoute: typeof AnalyticsCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/trial-balance': {
      id: '/accounting/trial-balance'
      path: '/accounting/trial-balance'
      fullPath: '/accounting/trial-balance'
      preLoaderRoute: typeof AccountingTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/pnl': {
      id: '/accounting/pnl'
      path: '/accounting/pnl'
      fullPath: '/accounting/pnl'
      preLoaderRoute: typeof AccountingPnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/ledger': {
      id: '/accounting/ledger'
      path: '/accounting/ledger'
      fullPath: '/accounting/ledger'
      preLoaderRoute: typeof AccountingLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/journal': {
      id: '/accounting/journal'
      path: '/accounting/journal'
      fullPath: '/accounting/journal'
      preLoaderRoute: typeof AccountingJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/balance-sheet': {
      id: '/accounting/balance-sheet'
      path: '/accounting/balance-sheet'
      fullPath: '/accounting/balance-sheet'
      preLoaderRoute: typeof AccountingBalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ModulesRoute: ModulesRoute,
  PricingRoute: PricingRoute,
  AccountingBalanceSheetRoute: AccountingBalanceSheetRoute,
  AccountingJournalRoute: AccountingJournalRoute,
  AccountingLedgerRoute: AccountingLedgerRoute,
  AccountingPnlRoute: AccountingPnlRoute,
  AccountingTrialBalanceRoute: AccountingTrialBalanceRoute,
  AnalyticsCustomersRoute: AnalyticsCustomersRoute,
  AnalyticsEmployeesRoute: AnalyticsEmployeesRoute,
  AnalyticsInventoryRoute: AnalyticsInventoryRoute,
  AnalyticsRevenueRoute: AnalyticsRevenueRoute,
  ApiChatRoute: ApiChatRoute,
  CrmCompaniesRoute: CrmCompaniesRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmDealsRoute: CrmDealsRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CustomersActivitiesRoute: CustomersActivitiesRoute,
  CustomersAnalyticsRoute: CustomersAnalyticsRoute,
  DocumentsFilesRoute: DocumentsFilesRoute,
  DocumentsFoldersRoute: DocumentsFoldersRoute,
  DocumentsRecentRoute: DocumentsRecentRoute,
  DocumentsSharedRoute: DocumentsSharedRoute,
  FinanceAccountsRoute: FinanceAccountsRoute,
  FinanceBudgetsRoute: FinanceBudgetsRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceIncomeRoute: FinanceIncomeRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FinanceTransactionsRoute: FinanceTransactionsRoute,
  HelpdeskKbRoute: HelpdeskKbRoute,
  HelpdeskTicketsRoute: HelpdeskTicketsRoute,
  HrAttendanceRoute: HrAttendanceRoute,
  HrDepartmentsRoute: HrDepartmentsRoute,
  HrDesignationsRoute: HrDesignationsRoute,
  HrEmployeesRoute: HrEmployeesRoute,
  HrLeaveRoute: HrLeaveRoute,
  HrPayrollRoute: HrPayrollRoute,
  InventoryCategoriesRoute: InventoryCategoriesRoute,
  InventoryMovementsRoute: InventoryMovementsRoute,
  InventoryProductsRoute: InventoryProductsRoute,
  InventoryWarehousesRoute: InventoryWarehousesRoute,
  ProjectsGanttRoute: ProjectsGanttRoute,
  ProjectsKanbanRoute: ProjectsKanbanRoute,
  ProjectsTasksRoute: ProjectsTasksRoute,
  ProjectsTeamRoute: ProjectsTeamRoute,
  PurchasesAnalyticsRoute: PurchasesAnalyticsRoute,
  PurchasesOrdersRoute: PurchasesOrdersRoute,
  PurchasesRequestsRoute: PurchasesRequestsRoute,
  PurchasesVendorsRoute: PurchasesVendorsRoute,
  RecruitmentCandidatesRoute: RecruitmentCandidatesRoute,
  RecruitmentInterviewsRoute: RecruitmentInterviewsRoute,
  RecruitmentJobsRoute: RecruitmentJobsRoute,
  RecruitmentPipelineRoute: RecruitmentPipelineRoute,
  ReportsCrmRoute: ReportsCrmRoute,
  ReportsFinanceRoute: ReportsFinanceRoute,
  ReportsHrRoute: ReportsHrRoute,
  ReportsInventoryRoute: ReportsInventoryRoute,
  ReportsSalesRoute: ReportsSalesRoute,
  SalesInvoicesRoute: SalesInvoicesRoute,
  SalesOrdersRoute: SalesOrdersRoute,
  SalesPaymentsRoute: SalesPaymentsRoute,
  SalesQuotationsRoute: SalesQuotationsRoute,
  SettingsCompanyRoute: SettingsCompanyRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  HelpdeskIndexRoute: HelpdeskIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
